### ISSUE TITLE
Default path for flow_png()

### ISSUE THREAD

**Issue by albersonmiranda** [moodymudskipper/funflow#31]
What about `getwd()` as default path instead of temp?

**Comment by moodymudskipper** [comment]
I don't think we should write a file to the working directory without being explicit about it, you might clutter your wd without realising it. 
Also path="foo.png" is fast to type, while writing to temp file and saving name takes more typing, and here is given for free.

**Comment by moodymudskipper** [comment]
Hi Alberson, I've removed flow_png, now you can use `flow_view()` with `out = "png"` or `out = "your_file.png"`
