### ISSUE TITLE
Non-numeric argument to binary operator

### ISSUE THREAD

**Issue by MichaelChirico** [moodymudskipper/funflow#7]
```
funflow::view_flow(data.table::fread)
```

> Error in cumsum(cfc_lgl) * cfc_lgl : 
>   non-numeric argument to binary operator

**Comment by moodymudskipper** [comment]
It comes from this :) : 

```
if (input == "" || length(grep("\\n|\\r", 
            input))) {
        }
        else { ...
```

I need to fix my code to support empty `{` calls, should be easy.

**Comment by moodymudskipper** [comment]
This is solved by https://github.com/moodymudskipper/funflow/commit/542fb3ebc43b9590d576b90e6de39bf5ceb8a11c

Note that the display has changed a bit, I added an exit not after the if blocks to join the yes and no before moving forward. It makes the view less compact but it's closer to the code, and solves some bugs.
